spring:
  security:
    oauth2:
      client:
        registration:
          discord:
            client-id: YOUR_DISCORD_CLIENT_ID
            client-secret: YOUR_DISCORD_CLIENT_SECRET
            scope: identify,email
            redirect-uri: "{baseUrl}/login/oauth2/code/discord"
        provider:
          discord:
            authorization-uri: https://discord.com/oauth2/authorize
            token-uri: https://discord.com/api/oauth2/token
            user-info-uri: https://discord.com/api/users/@me
            user-name-attribute: id
