server:
  port: ${PORT:8082}

spring:
  application:
    name: artist-service

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      maximum-pool-size: 2               # 최대 커넥션 수
      minimum-idle: 1                    # 최소 유휴 커넥션 수
      idle-timeout: 10000                # 커넥션이 유휴 상태로 유지되는 최대 시간 (ms)
      max-lifetime: 300000               # 커넥션의 최대 수명 (ms) → 기본값은 30분
      connection-timeout: 3000           # 커넥션 풀에서 커넥션 얻을 때까지 기다리는 최대 시간 (ms)
      validation-timeout: 2000           # 커넥션 검증 응답 대기 시간 (ms)
      leak-detection-threshold: 15000    # 커넥션 누수 감지 시간 (ms)

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  cloud:
    config:
      name: artist-service

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      group-id: artist-service-group
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

jwt:
  secret: ${JWT_SECRET}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
