server:
  port: 8000

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      default-filters:
        - AddRequestHeader=X-Request-Foo, Bar
      routes:
        - id: song-service
          uri: lb://song-service
          predicates:
            - Path=/songs/**
        - id: lyrics-service
          uri: lb://lyrics-service
          predicates:
            - Path=/lyrics/**
        - id: artist-service
          uri: lb://artist-service
          predicates:
            - Path=/artists/**
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**

    config:
      name: api-gateway

  security:
    oauth2:
      resourceserver:
        jwt:
          secret-key: ${JWT_SECRET}

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka
