server:
  port: 8000

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      default-filters:
        - AddRequestHeader=X-Request-Foo, Bar
      routes:
        - id: song-service
          uri: http://song-service:8080
          predicates:
            - Path=/songs/**
        - id: lyrics-service
          uri: http://lyrics-service:8080
          predicates:
            - Path=/lyrics/**
        - id: artist-service
          uri: http://artist-service:8080
          predicates:
            - Path=/artists/**
        - id: auth-service
          uri: http://auth-service:8080
          predicates:
            - Path=/auth/**

    config:
      name: api-gateway


  security:
    oauth2:
      resourceserver:
        jwt:
          secret-key: ${JWT_SECRET}


