server:
  port: 8000

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      default-filters:
        - AddRequestHeader=X-Request-Foo, Bar
      routes:
        - id: auth-service
          uri: ${AUTH_SERVICE_URI:http://localhost:8080}
          predicates:
            - Path=/auth/**

        - id: user-service
          uri: ${USER_SERVICE_URI:http://localhost:8081}
          predicates:
            - Path=/user/**

        - id: artist-service
          uri: ${ARTIST_SERVICE_URI:http://localhost:8082}
          predicates:
            - Path=/artists/**

        - id: song-service
          uri: ${SONG_SERVICE_URI:http://localhost:8083}
          predicates:
            - Path=/songs/**

        - id: lyrics-service
          uri: ${LYRICS_SERVICE_URI:http://localhost:8084}
          predicates:
            - Path=/lyrics/**

    config:
      name: api-gateway

  security:
    oauth2:
      resourceserver:
        jwt:
          secret-key: ${JWT_SECRET}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}

springdoc:
  swagger-ui:
    urls:
      - name: auth-service
        uri: /auth-service/v3/api-docs
      - name: user-service
        url: /user-service/v3/api-docs
      - name: artist-service
        url: /artist-service/v3/api-docs
      - name: song-service
        url: /song-service/v3/api-docs
      - name: lyrics-service
        url: /lyrics-service/v3/api-docs

