spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      default-filters:
        - AddRequestHeader=X-Request-Foo, Bar
      routes:
        - id: song-service
          uri: http://localhost:8083
          predicates:
            - Path=/songs/**
        - id: lyrics-service
          uri: http://localhost:8084
          predicates:
            - Path=/lyrics/**
        - id: artist-service
          uri: http://localhost:8085
          predicates:
            - Path=/artists/**

    config:
      name: api-gateway

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/oauth2/jwks  # Auth 서버가 있다면 설정

server:
  port: 8000
