server:
  port: 8080

spring:
  application:
    name: artist-service

  datasource:
    url: jdbc:mariadb://croonling-mariadb.cd8oeo4qscnq.ap-northeast-2.rds.amazonaws.com:3306/croonling
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  cloud:
    config:
      name: artist-service

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      group-id: lyrics-service-group
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer


