spring:
  application:
    name: song-service

  datasource:
    url: jdbc:mariadb://localhost:3306/song_db
    username: song_user
    password: song_pass

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  cloud:
    config:
      name: song-service

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: lyrics-service-group
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

server:
  port: 8080
