server:
  port: 8082

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:mariadb://localhost:3306/user_db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect

  cloud:
    config:
      name: user-service

logging:
  level:
    org.hibernate.SQL: debug
