name: Deploy Discovery Server to ECS

on:
  push:
    paths:
      - "CroonLing-MSA/discovery-server/**"
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin 407337236871.dkr.ecr.ap-northeast-2.amazonaws.com

      - name: Build and push Docker image
        run: |
          docker build -t discovery-server ./CroonLing-MSA/discovery-server
          docker tag discovery-server:latest 407337236871.dkr.ecr.ap-northeast-2.amazonaws.com/croonling/discovery-server:latest
          docker push 407337236871.dkr.ecr.ap-northeast-2.amazonaws.com/croonling/discovery-server:latest

      - name: Deploy to ECS
        run: |
          aws ecs update-service \
            --cluster croonling-cluster \
            --service discovery-server \
            --force-new-deployment
